# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master


steps:
- task: browserstackcom.browserstack-vsts-extension.browserstack-config-task.BrowserStackConfig@0
  displayName: 'BrowserStack configuration setup'
  inputs:
    BrowserStackServiceEndPoint: 'BrowserStack Connection'
    browserstackLocal: true
    bsLocalOptions: '{"verbose": true, "forceLocal": true} '
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- script: npm install
- script: npm install browserstack-local
- script: npm install selenium-webdriver
- script: export BROWSERSTACK_USERNAME="abhishekmordani2"
- script: export BROWSERSTACK_ACCESS_KEY="fmoKDwWonczWxsfT4egK"
- script: node sampleMob.js
- script: node pac_check.js


- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
